microsoft/GSL

include/array_view.h
include/gsl.h
tests/CMakeLists.txt
tests/array_view_tests.cpp
tests/owner_tests.cpp

This PR adds the missing owner<T> and corrects the implementation of array_view::sub() to be as per earlier prototypes (in other words, to be correct).

Added missing owner<T>, corrected array_view::sub().

---

README.md

This PR fixes the broken [isocpp.org](https://isocpp.org) link mentioned in #19.

Fix the broken isocpp.org link in README.md.

---

include/fail_fast.h

Missing header <stdexcept> in fail_fast.h #23

Issue #23   missing header <stdexcept> 

---

README.md

It's a minor change - awesome project btw! We'll totally adopt that for the PSPDFKit SDK.

Fixes spelling of Xcode

---

include/gsl.h
tests/maybenull_tests.cpp

Add tests for maybe_null_dbg and fix bug where comparing two of them results in an implicit conversion to T, and a call to get().

Fix issue #45: comparing two maybe_null_dbg's can cause fail_fast

---

include/gsl.h

for eg consider this case
````cpp
string value = "someVeryLongErrorMessageIAm";
finally([value] { PrintErrorMessage(value); } 
````
With the current changes before the call to PrintErrorMessage there will be 3 calls to copy constructor for string(1 when it's captured in closure, 2nd when finally is called and 3rd when it's passed to Final_act) . With my patch there will be 1 call to the copy constructor and 2 to the move constructor for the scenario in example, so 2 potential deep copies will be saved for  objects that support move semantics and are passed to or are captured in closures in call to  <code> finally </code>. 
Validated that code builds from project root, and all tests pass after my change. Also validated that indeed copy constructor calls are saved for objects that support …

Guide::finally can make use of move semantics

---

include/gsl.h
tests/maybenull_tests.cpp
tests/notnull_tests.cpp

This is in accordance with the GSL.View guidance on not_null and maybe_null
types in the CppCoreGuidelines document.
It is an update of the commit made for #63, except it's been updated so that the check is performed on all types that are actually nullable.

not_null and maybe_null variants should only work on nullptr-assignable types.

---

include/array_view.h

Just silence 5 warnings of my compiler.

fix clang -Wunused-parameter warnings

---

include/gsl.h
tests/maybenull_tests.cpp

In my opinion you shouldn't have to test maybe_null_dbg's before using them to assign or construct another maybe_null_dbg.

Fix issue #49

---

include/gsl.h
tests/utils_tests.cpp

The move constructor of Final_act is updated to accept a non-const r-value reference. It also properly moves from the r-value function object member to the function object member of the object being constructed during the move operation. It now has a boolean to indicate whether or not the function object should be invoked in the destructor so that temporary objects that have been moved from do not invoke the function object improperly, removing dependence on copy elision for correct behavior. Finally, a test is added to verify that Final_act objects can be moved, if necessary. This resolves the issues discussed in issue #42.

Fixing move constructor/semantics of Final_act

---

include/array_view.h
include/string_view.h
tests/array_view_tests.cpp
tests/bounds_tests.cpp

This is the first of a series of changes to `array_view` and `string_view` to bring them into line with the proposals we submitted to WG21 at the Kona, USA meeting to have the types considered for inclusion in the standard C++ library.
At the meeting we got valuable feedback on aspects of the design - including naming - and more changes will show up shortly so that this GSL implementation can accurately track the revised proposal for the next WG21 meeting.
As part of the overall process, I'll also be adding specifications for the GSL types to the CppCoreGuidelines repository in the near future.

Changing index type for array_view

---

include/gsl.h
include/span.h

use "#undef" instead of "#pragma undef"

fixes pragma undef warnings in MSVC2013

---

include/span.h

Forgot about NOMINMAX as a superior solution (and duffed up the workaround anyway)....not enough coffee this afternoon!

Remove unnecessary workaround for max macro

---

include/span.h

This silences implicit sign conversion warnings when constructing span
from containers which return size_t from size().

Added explicit cast to size_type in span constructor

---

include/span.h

This should prevent some accidental implicit conversions from span to integers.

Made conversion of span<> to bool explicit

---

include/gsl_assert.h
include/gsl_util.h
include/span.h
tests/CMakeLists.txt
tests/span_tests.cpp
tests/strided_span_tests.cpp
tests/string_span_tests.cpp

Warning: breaking changes!
This commit makes a number of changes to `span` to make it match the current GSL design (which I will publish soon to the CppCoreGuidelines repository). It also addresses a number of annoyances about the existing implementation (not using `narrow_cast` where appropriate, for example). I also took this opportunity to run clang-format against span.h. Hopefully that makes it more consistent.
`string_span' will be dealt with separately soon. `strided_span` is likely to be removed in the near future but lives on for now.

Reworked span to match GSL design.

---

include/span.h

Corrected a single missing rename of bytes() to size_bytes().

Correct missing rename of bytes() to size_bytes()

---

include/span.h
include/string_span.h

Hi,
I had some small issues when using GSL with VS2013. Maybe, you would like to integrate some of my fixes back in your code.
- First, the macro max defined by Windows.h conflicts with std::max, so I temporarily undefined max in span.h, so that it works for windows users even if NOMINMAX is not defined.
- Second, with VS2013, the move constructors cannot be defaulted so I had to implement them for string_span.
- Third, with VS2013, there is a pragma warning pop without any corresponding pragma warning push in string_span.h
Finally, I have some trouble compiling the unit tests for string_span with VS2013. There is an ICE because of the constructor of string_span taking a span. I am trying to work around it but I don't have a good workaroung yet.
Regards

VS2013: macro max, move ctors, pragma warning

---

include/span.h
include/string_span.h

Hi,
I fixed an ICE when using the string_span ctors that have a dummy defaulted template type parameter used for SFINAE.
I replaced the template type parameter by a function parameter.
Warning : I am not an expert of std::enable_if, so I may have introduced some mistakes.
Note : I checked again that I have VS2013 U5, but maybe my installation is buggy and the ICE is due to that. In this case feel free to ignore my pull request :-)

Vs2013 fix string span ctors

---

include/span.h
include/string_span.h

Finally, when compiling the unit tests, there was still an error when calling std::equal. VS2013 does not have the overload that takes 4 iterators. So I used the overload that takes 3 iterators.
Again, this may be due to a bad installation of VS2013 on my PC...

Vs2013 fix std equal call

---

include/string_span.h

`string_span.h` uses `std::string`, but `<string>` is not included.

Fix missing #include <string> in string_span.h

---

include/string_span.h
tests/string_span_tests.cpp

Removed inconvenient zstring_builder class and added zstring_span wrapper type to convers zero terminated spans into legacy zero terminated strings. Added tests (with one usage case)

Added zstring_span and removed zstring_builder to support legacy strings

---

.gitignore
.gitmodules
.travis.yml
tests/CMakeLists.txt

This should address the following issue: https://github.com/Microsoft/GSL/issues/47
Note that I invoke git within cmake to automatically initialize the submodule. This assumes that git is in the path.

Making unittest-cpp a submodule.

---

include/gsl_util.h
include/span.h
include/string_span.h

This will prevent warnings about the GSL implementation from needlessly annoying users of CppCoreCheck. A more targeted set of suppressions will go into a future revision of the GSL.

Suppressed CppCoreCheck warnings.

---

include/gsl_util.h
tests/at_tests.cpp

initializer_list do not have subscript operator, so the generic container overload of gsl::at fails to compile.
This commits adds an overload of gsl::at for initializer_lists, using *(initializer_list::begin()+index) instead of subscript operator, and associated test

gsl::at overload for initializer_list

---

CONTRIBUTING.md
README.md

Because [C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md) is using the name “Guideline support library” instead of “Guidelines support library”.

Fix inconsistent naming

---

gsl/string_span

Not all platforms have support for strnlen (e.g. cygwin) as this is a non-standard function. This patch provides a custom implementation of strnlen for these platforms.

Fix issue: Provide platform support for strnlen

---

gsl/span
tests/span_tests.cpp

span being a view and not a container, the generic version of gsl::at is not valid any more for span.
This commits adds a specialization of gsl::at for span

Specialize gsl::at for span

---

gsl/gsl
gsl/gsl_byte
gsl/gsl_util
gsl/multi_span
gsl/span
gsl/string_span

This PR resolves issue #340.
To give the commented-out `constexpr` the appearance of a single element, there's no whitespace between `constexpr` and `/*`, `*/` .

Define constexpr as /*constexpr*/ when unavailable (also noexcept)

---

gsl/gsl_byte
tests/byte_tests.cpp

I have added the to_byte method and updated the unit tests.
This gives slightly nicer syntax than static_cast, is better than the
c-style cast used in the unit test.
See: https://github.com/Microsoft/GSL/issues/329#issuecomment-240588515
I have tested my change on:
* VS2013
* VS2015
* Apple LLVM version 7.3.0 (clang-703.0.31)
Hopefully everything passes

Added to_byte method for issue #329

---

gsl/gsl_byte

Added inlines to avoid these compilation warnings on msvc13 where constexpr is not available
warning LNK4006: "enum gsl::byte & __cdecl gsl::operator|=(enum gsl::byte &,enum gsl::byte)" (??_5gsl@@YAAEAW4byte@0@AEAW410@W410@@Z) already defined in Algorithm.obj; second definition ignored

Added inline to fix compilation warnings on msvc 2013

---

gsl/multi_span
tests/multi_span_tests.cpp

I augmented the tests of multi_span to show that you can pass negative indices and they are not detected properly. The second commit to my branch fixes the `Expects()` checks that cause the problem, so that the new checks pass.
```
TEST(bounds_checks)
{
int arr[10][2];
auto av = as_multi_span(arr);
fill(begin(av), end(av), 0);
// ...
CHECK_THROW(av[-1][0], fail_fast); // ... does not throw before the fix
CHECK_THROW((av[{-1, 0}]), fail_fast);  // ... does not throw before the fix
}
```

Negative indices to multi_span are not flagged with neither exception nor abort.

---

tests/multi_span_tests.cpp

I assume those checks where meant to compare `multi_span` variables that where initialized with `nullptr`, not `nullptr_t` variables.

fix wrong types in multi_span_test (<comparison_operators>)

---

gsl/gsl_byte

Turn off warning about function-styl casts in gsl_byte

---

gsl/multi_span

* Make `BoundsRanges<dynamic_range, ...>::m_bound` non-`const` and private
* Remove various defaulted copy constructor/assignment declarations from `BoundsRanges` specializations whose only effect is to needlessly suppress the generation of moves
* Remove the hackish `static_bounds::operator=(const static_bounds&)`. The implicitly generated default is now sufficient.
Technically, the `new` expression itself:
```c++
new (&m_ranges) MyRanges(otherBounds.m_ranges); 
```
has defined behavior. The problem is that any access to the new object created atop `m_ranges` through the name of or pointers to the object that previously existed there does result in UB per [basic.life]/7.3.

[span] Fix UB hack in static_bounds::operator=(const static_bounds&)

---

gsl/string_span

Cygwin recently did an update that broken string_span again. The original update had to provide a custom strnlen function because Cygwin doesn't implement this (it's a non-std extension). We never added wchar_t support, and the Cygwin update now breaks on exactly this. This patch provides the missing wchar_t.

Fix compilation issues with Cygwin

---

gsl/gsl_assert

We should be using branch prediction on asserts as these conditions are known to be unlikely, therefore we should be optimizing the likely case. These macros are similar to what the Linux kernel uses. Not really sure what Visual Studio does so at the moment these are disabled for VS.

Add branch prediction to Ensures / Expects

---

gsl/span

Standard containers return size_t which is signed.  Therefore implicit conversion to index_type throws a warning which causes compiler errors on -Wall.  This static casts to avoid this.  
Passes tests on gcc version 6.2.0 20160914 (Ubuntu 6.2.0-3ubuntu15)

For span, fix size_t to index_type conversion warning 

---

gsl/string_span

This implements the changes discussed in #391 . The end goal of the changes is to support arm-none-eabi though it should be more portable overall.

[#391] Remove strnlen and use consistent length type

---

tests/CMakeLists.txt

'make install' should install the GSL library (ie. the headers),
not the tests.
It still installs the UnitTest++ headers, but that will be more
complex to fix, as GSL just imports UnitTest++ as a git submodule,
and the install command propagates down to UnitTest++'s
CMakeLists.txt.

Don't install tests

---

gsl/gsl_util

Based on [F19](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f19-for-forward-parameters-pass-by-tp-and-only-stdforward-the-parameter), I believe `gsl::narrow_cast` should be implemented using forward semantics.

Update narrow_cast to use std::forward

---

gsl/span
tests/span_tests.cpp

As per this discussion:
https://github.com/Microsoft/GSL/issues/402
This patch adds support for at() to gsl::span

Adds gsl::span::at()

---

gsl/string_span

When building with GCC 5.4, the compiler spits out a warning about
the following:
warning: assuming signed overflow does not occur when assuming
that (X - c) > X is always false [-Wstrict-overflow]
This patch fixes this issue.

Fix compiler warning

---

gsl/gsl_util
gsl/span
tests/at_tests.cpp

gsl::at should use std::ptrdiff_t instead of size_t. This patch
fixes that, and adds missing unit tests

Fix gsl::at's use of size_t

---

gsl/span

remove noexcept on functions that use Expects macro (because Excepts actually can throw which can lead to std::terminate)

remove noexcept on functions that use Expects macro

---

gsl/span
tests/span_tests.cpp

This patch adds support for std::unique_ptr to the gsl::span
class instead of having to manually grab the pointer from
a std::unique_ptr.
It was suggestd that we also add support for std::shared_ptr,
but no array syntax exists for this class, and the element
types don't match. Until the following is accepted, I suggest
support for std::shared_ptr is left out:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4077.html
For reference, this is part of the following issue:
https://github.com/Microsoft/GSL/issues/402

Add std::unique_ptr support to gsl::span

---

tests/span_tests.cpp

The unique_ptr / shared_ptr patch introduced a compiler
warning. This corrects that issue.

Cleanup compiler warnings

---

gsl/span
tests/span_tests.cpp

This patch provides a make_span function to simplify the
creation of spans until C++17 is available. In addtion
this patch updates the unit tests to includes tests that
verify this new functionality.

Add make_span()

---

CMakeLists.txt
gsl/gsl_algorithm
tests/CMakeLists.txt
tests/algorithm_tests.cpp

**Update:** The original eiscription is completely outdated -- see the following posts.
-----------------
**Original:**
This PR implements a copy function for span similar to what was mentioned in issue #248. However, instead of void, it returns a span representing the remaining space in the destination span.
There are probably a lot of style issues to be addressed and I'd be happy to incorporate any feedback, but my main question at the moment would be if the design is OK and if that function should be put into the `span` header as I did or into some separate utility / algorithms header.

Add a copy function for span as mentioned in issue  #248

---

tests/multi_span_tests.cpp

This warning was seen with gcc 6.2.0

Fix a signed/unsigned comparison warning.

---

gsl/multi_span

Rearranged preprocessor code at end of file multi_span

Fix #pragma warning push/pop mismatch in multi_span (Issue #431)

---

gsl/gsl_byte

type_traits are needed for gsl_byte to be used in clang 3.9.1

Fix gsl_byte in clang 3.9.1

---

gsl/span
tests/span_tests.cpp

..so that `std::is_default_constructible<gsl::span<int, 42>>::value` doesn't `static_assert`. Makes spans of static extent usable with range-v3.

Make is_default_constructible work for spans.

---

include/gsl/gsl_byte

I apparently lied when I said I had reverted all of these changes to the `constexpr` macros. Causes warning spew when building with VS2013.

Revert change to the definition of constexpr macro in gsl_byte from #446

---

tests/algorithm_tests.cpp

Now that the STL respects /W4, this test that uses `std::copy_n` to copy a span of ints to a span of chars triggers "warning C4244: '=': conversion from 'int' to 'char', possible loss of data". Switch the source & destination spans to `short` and `int` to maintain the test's cross-type nature but without narrowing.

Silence warning in algorithm_tests with VS2017

---

include/gsl/gsl

* constexpr all the things.
* remove `operator=(const T&)`
* it leaves `*this` in an invalid state if `ensure_invariant` fails
* implicitly converting the `T` to `not_null` and then assigning is in every way superior.
* Enforce the invariant after conversion from `not_null<U>`. For a (poorly designed) user type, a non-null `U` could convert to a null `T`. For pointers, the check should optimize away.
* remove the converting assignment operator; again let the conversion constructor and self-assignment operator do the work.
*  Define macro `GSL_ASSUME` in `gsl_util` to semi-portably inform the optimizer that a predicate MUST hold. Use `GSL_ASSUME` in `not_null::get`.
* Cover the remaining pointer arithmetic operations as Wakely suggests in issue #447.
* Implement unary `+`, because it's …

not_null updates:

---

include/gsl/gsl

Hippomocks, which is a popular mocking engine for C++ uses operator<< on pointers and gets confused about gsl::not_null not having this operator.

add gsl::not_null operator<<

---

include/gsl/string_span

Leaving the arguments as const-pointer since it's not really harming anything. Compilation of tests succeeds & all tests pass (though this change shouldn't have any runtime effects). CppCoreCheck with VS 2017 RC also passes without issue.

[Issue #451] Updating length_func<CharT>::operator() to accept pointer-to-const

---

include/gsl/gsl_assert

* `GSL_LIKELY`/`_UNLIKELY` always contextually convert their argument to `bool`.
* Add macro `GSL_ASSUME(cond)` to inform the optimizer that the predicate `cond` must hold.
* Reimplement `Expects` & `Ensures` as expressions for flexibility and correctness. (Think about `if (cond1) Expects(cond2); else goto fail;`)
* `Expects` and `Ensures` `GSL_ASSUME` their predicate when `GSL_UNENFORCED_ON_CONTRACT_VIOLATION` is defined.

gsl_assert changes:

---

include/gsl/string_span
tests/bounds_tests.cpp
tests/byte_tests.cpp
tests/span_tests.cpp
tests/strided_span_tests.cpp
tests/string_span_tests.cpp
tests/utils_tests.cpp

This PR fixes some of the warnings that the c++ core checker throws in VS2017. Mostly const correctnes "issues" and a few suppressions around pointer arithmetic.

Fix some corechecker warnings

---

include/gsl/gsl_assert

Fixes #298.
Contract violations are logic errors.

fail_fast should derive from logic_error

---

include/gsl/gsl_util
tests/at_tests.cpp

* `initializer_list` overload returns by value to avoid lifetime issues
* generic overload uses expression SFINAE to work with any type that has member `size()` and operator `[]`, which notably includes `const`/non-`const` `vector` and `array`.
* Add test coverage for const objects, rvalue `initializer_list`s, and `constexpr` usage.
Fixes #357.

gsl::at updates:

---

include/gsl/gsl
tests/notnull_tests.cpp

This pull requests adds comparison operators support for gsl::not_null on smart pointers such as shared_ptr.
Comparison already worked for `not_null<raw pointer>`. Now not_null smart pointers can also be compared.

Added support of not_null<smart_ptr> comparison

---

.gitmodules

- unittest-cpp's wiki submodule used to contain items that had invalid path names on windows.
- updated to latest unittest-cpp that includes a fix for that and made the gsl submodule point back to the origin.
- resolves #438

Fix Bad Paths On Windows In UnitTest-Cpp Submodule

---

include/gsl/span

Currently I'm working on project which involves a lot of `span`s and mocking via Google Mock. Unfortunately a lot of standard matchers requires `value_type` type definition inside container which `gsl::span` lacks. 
This pull request add `value_type` type definition inside `gsl::span`

Add value_type to span

---

include/gsl/gsl
include/gsl/gsl_algorithm
include/gsl/gsl_assert
include/gsl/gsl_byte
include/gsl/gsl_util
include/gsl/multi_span
include/gsl/span
include/gsl/string_span
tests/algorithm_tests.cpp
tests/assertion_tests.cpp
tests/at_tests.cpp
tests/bounds_tests.cpp
tests/byte_tests.cpp
tests/multi_span_tests.cpp
tests/notnull_tests.cpp
tests/owner_tests.cpp
tests/span_tests.cpp
tests/strided_span_tests.cpp
tests/string_span_tests.cpp
tests/utils_tests.cpp

Project files were not following the clang-format style. For people
using IDEs were clang-format is always run after a save this would
cause unwanted changes.
This commit only applies "clang-format -i" to files.
See #486

Reformat files to follow clang-format style

---

include/gsl/span

Fixes #510.
* Constrain the converting constructor to not participate in overload resolution when `IsConst` is true, so that it is never a copy constructor.
* Use Default Member Initializers for `span_iterator`'s data members so that the default constructor can be explicitly defaulted.
* Declare all members of `span_iterator` `GSL_NOEXCEPT`: they only throw when contract violations throw.
* Don't use `&` in `operator->` since evil types may overload it.

span_iterator: converting constructor isn't a copy constructor

---

include/gsl/span

Moved it to the correct position

GSL_NOEXCEPT should appear before the initialization list

---

include/gsl/multi_span

This causes an error on clang with all warnings.

Fix use of 0 instead of nullptr warning

---

include/gsl/gsl
tests/notnull_tests.cpp

dereferencing operator added in PR #513 returned a copy of the object
instead of reference to it.
Adding decltype(auto) as return type of operator* fixes this issue.

Fixes dereferencing operator issue #517 introduced in PR #513

---

include/gsl/gsl_byte
tests/CMakeLists.txt

This small change allows the GSL to use the std::byte implementation from MSVC when it is available.

Use std::byte when available.

---

include/gsl/multi_span

The current constructor is not called even by the unit test (it is currently calling the "container" constructor instead). I mimicked the constructor taking a non-const std::array to fix the issue #522.

Fix multi_span constructor taking a const std::array (#522)

---

include/gsl/gsl_byte

This fails to compile on gcc 7.1 because it tries to include cstddef inside the gsl namespace.

Fix STD_BYTE cstddef include in wrong place

---

include/gsl/gsl
include/gsl/gsl_byte
include/gsl/gsl_util
include/gsl/multi_span
include/gsl/span
include/gsl/string_span

As has been previously announced, we are no longer supporting VS 2013 for the GSL now that VS 2017 has been released (some time ago).

Remove VS2013 workarounds.

---

include/gsl/gsl_byte

Because the comment "this tests if we are under GCC or Clang with enough -std:c++1z power to get us `std::byte`" is wrong: the correlation between compiler and standard library versions is at best loose in the open source world. There is no reasonable way for a third party library to determine if the implementation supports `std::byte`, so users must be able to override our guess when it is wrong.
Of course `byte` isn't implementable as a pure library feature in C++, so the fallback implementation is not portable. It would probably be better - at least the behavior would be portable - for the library to use `unsigned char` in place of `byte` absent implementation support for `std::byte`.

Allow users to override GSL_USE_STD_BYTE

---

.gitignore
tests/CMakeLists.txt

Catch was being installed to the root of the cmake project. This
violated the source code tree itself and would not work at all if GSL
was being consumed with add_subdirectory.
CMake will now install catch to the build tree under /dependencies.
This fixes #538

Fix catch installation issue

---

CMakeLists.txt
tests/CMakeLists.txt

This removes dependency on Git for tests. This eliminates CMake errors in environments without installed Git. Also an user can force to use the Catch library which is installed in `/usr/include` or something, if (s)he defines the _CMAKE_DISABLE_FIND_PACKAGE_Git_ variable for CMake invocation. Like this
cmake /path/to/GSL -DCMAKE_DISABLE_FIND_PACKAGE_Git=1

Use system version of the Catch test framework

---

include/gsl/gsl_algorithm

using the GSL with MSVC 2017 causes the following warning"
`'std::copy_n::_Unchecked_iterators::_Deprecate': Call to 'std::copy_n'`
This patch removes this since the point of this code is to deal with this issue.

turning off warning

---

CMakeLists.txt

When integrating the GSL as an external dependency, it is usually unnecessary to build and run the unit-tests.

Adds an option to disable test generation

---

include/gsl/string_span
tests/string_span_tests.cpp

Made `string_length()` generic (templated) Removed overloads & specialized classes
Creating *string spans* using `char16_t` and `char32_t` was not possible without creating new specializations and function overloads.
This patch makes `details::string_length()` generic removing the need to extend the overloads and specializations.
This PR intends to fix Issue #542

Made string_span details::string_length() generic (Fix issue #542)

---

include/gsl/gsl_byte

* Only check that `_HAS_STD_BYTE` is defined to a non-zero value

Update std::byte detection in gsl_byte for MSVC

---

include/gsl/multi_span
include/gsl/pointers
include/gsl/string_span

From what I understand [from this discussion](https://github.com/Microsoft/GSL/pull/114) looks like Dummy was needed for VS2013. Since it seems like we don't support that anymore I removed the Dummies.

Drop "Dummy" from enable_if in templates

---

tests/CMakeLists.txt

Update Catch to version 2.
Version 1 would capture exceptions by value (which would make clang dislike code at times) version 2 fixes that.

Updates catch to version 2.0

---

include/gsl/multi_span

In C++17 std::iterator is marked duplicated, which resulted in warnings during compilation. Added handwritten usigs for traits.
Fixes: https://github.com/Microsoft/GSL/issues/587

Remove std::iterator inheritance from multi_span.

---

include/gsl/gsl_util

Should fix #128. There is an old PR #129 that does the same, but it never got merged and now has merge conflicts.
So if this gets merged we should probably close #128 and #129.

rename final_act to final_action

---

CMakeLists.txt
README.md

changes:
- minimal cmake version updated to 3.7(first version with .natvis file handling)
- updated cmake version in readme file
- GSL.natvis file is added only to VS projects
*.natvis file support was added to cmake in version 3.7: https://cmake.org/cmake/help/v3.7/release/3.7.html#generators

Visual Studio Debug Visualizers support

---

include/gsl/gsl_assert

Fixes #607.
Drive-by: use '?:' to contextually convert to bool in the fallback definition of `GSL_ASSUME`

Don't use clang's __builtin_assume as an optimizer hint

---

GSL.natvis

Commit 6e2e207c8d renamed final_act to final_action. Do this also in
GSL.natvis.

Rename final_act in GSL.natvis

---

include/gsl/string_span

Resolves compiler code analysis warning ...\gsl\include\gsl\string_span(101): warning C26496: The variable 'str_span' is assigned only once, mark it as const (con.4: https://go.microsoft.com/fwlink/p/?LinkID=784969).

add const in string_span

---

CMakeLists.txt

`CMAKE_VERSION_MAJOR` is just the first component of the CMake version (e.g. 3 for 3.10.1) which compares less than `3.7.9` if it is less than 3. The proper variable to compare is `CMAKE_VERSION` which contains the full version number.

Fix wrong check of the CMAKE_VERSION

---

include/gsl/gsl_util

Initialize `invoke_` in-class, according to http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c48-prefer-in-class-initializers-to-member-initializers-in-constructors-for-constant-initializers

Use in-class init for final_action members (C.48)

---

include/gsl/multi_span

Prevents MSVC code analysis warning
...\gsl\include\gsl\multi_span(1055): warning C26440: Function 'gsl::dim_t<-1>::dim_t<-1>' can be declared 'noexcept' (f.6: http://go.microsoft.com/fwlink/?linkid=853927).

add constexpr and noexcept in multi_span

---

include/gsl/multi_span

Fixing a bug in the != operator in the gsl::index class

gsl::index bug fix

---

include/gsl/gsl_util
include/gsl/multi_span
include/gsl/span
tests/multi_span_tests.cpp
tests/strided_span_tests.cpp
tests/utils_tests.cpp

renamed existing gsl::index to gsl::span_index in order to resolve name collision.
added gsl::index as described in ES.107: Don't use unsigned for subscripts, prefer gsl::index
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-subscripts
fixes: #617

add gsl::index typedef

---

include/gsl/span

VS 2017 warns me that make_span could be made constexpr.
This PR gets rid of the warning.

constexpr for make_span

---

include/gsl/span
tests/span_tests.cpp

This PR modifies the return type of the templated version of `span::subspan()` so that it returns a fixed-sized span wherever possible. This is important for encouraging optimization of code that uses `subspan()`.
Writing the tests for this made me actually use `span::extent` which made me realize that it does not work unless you are using a C++17-compliant compiler, so I also added a workaround to make `span::extent` available on C++11/14 compilers until we can all live in the better world of C++17. ;-)

Fix return type of templated span.subspan()

---

include/gsl/span

This addresses issue #621 in a more general way than pull request #622.  By adding `_Unchecked_type` to `span_iterator`, the Microsoft standard library will assume that `span_iterator` is checked, which it is.
Pull request #622 wraps the `span_iterator` in a `checked_array_iterator`, which is redundant because `span_iterator` is already checked.  Furthermore, #622 is only a very specific fix for `gsl::copy` in particular.  The change in this pull request will allow you to use `span_iterator` for any of the STL algorithms without warning.

Fix warning 4996 on Microsoft compiler

---

include/gsl/span
include/gsl/string_span

- simplified storage constructors to reduce branching
- eliminated null check for constructor from array
- removed GSL_NOEXCEPT from span

simplified constructors and removed GSL_NOEXCEPT

---

include/gsl/gsl_assert

This fixes the build with clang 7 which introduces a new warning
`-Wreturn-std-move` which warns about needless copies when a move
operation is available (see https://reviews.llvm.org/rL329914).
We take the exception object by uref so we should throw the forwarded
version.

Make gsl::details::throw_exception not copy exception object

---

include/gsl/gsl_util

This suppresses warning C26432 on VS2017. Fixes issue #653.

final_action move assignment operator =delete against C26432

---

include/gsl/string_span

This changes fixes the warning
> ...\..\GSL\include\gsl/string_span:701:2: warning: namespace 'gsl' ends with a comment that refers to a wrong namespace 'GSL' [google-readability-namespace-comments]
} // namespace GSL
> ^~~~~~~~~~~~~~~~~
>   // namespace gsl

Fix clang-tidy warning about wrong comment on closing namespace

---

include/gsl/pointers
tests/notnull_tests.cpp

not_null constructor is now explicit

---

CMakeLists.txt

This patch reverts the CMake minimum back to 3.1.3, re-enabling support for Cygwin, without effecting the original intention. 
Signed-off-by: Rian Quinn <rianquinn@gmail.com>

Revert CMake Minimum

---

README.md

Reverted to the previous cmake version requirement. Some common Linux distributions still do not support cmake 3.7 (Mint, Ubuntu LTS).

Cmake version requirement updated in README

---

include/gsl/gsl_byte

C++20 defines `std::byte*` to have the same aliasing properties as
`char*`. Hence, we mark it with the `__may_alias__` attribute under gcc
and clang.
Fixes #663 
(Actually couldn't find whether this requirement is already in C++17 or not but gcc and clang already implement this in the compiler, trusting Niall on this part)

Add __may_alias__ attribute to gsl::byte

---

include/gsl/span

and cleanup `span_iterator` non-member operators.

[span] Tell MSVC how to avoid range-checking 

---

include/gsl/span

This is Billy ONeal's PR #682 with a typo fixed.
- See corresponding change here:
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/msvc/commit/ca77129308c775f422ecef0c01ad460f75c462ad
That change officially exposes the STL's range checking machinery,
available in MSVC++ "15.8"+
This change augments GSL span::iterator to call into that newly exposed
machinery.
- _Verify_range(cit, cit)
Requests that the iterator type check that the parameters form a valid
[First, Last) range iterator pair. This replaces _DEBUG_RANGE and
supporting machinery. The standard library provides a version for
pointers under _IDL != 0; otherwise they are normally provided via
hidden friend functions. Note that declaring some of these hidden
friends for "wrapper" iterators like move_iterator and …

Add usage for check-and-unwrap of MS STL iterators

---

.travis.yml
include/gsl/multi_span
include/gsl/span

this is a quite pragmatic solution - it simply disables the specific warning

another trial to fix gcc build (gcc 7)

---

include/gsl/multi_span

It fixes the warnings I get with g++ 8.0.1:
```
In file included from ./GSL/include/gsl/gsl:24,
from src/array_copy.cpp:10:
./GSL/include/gsl/multi_span: In constructor ‘constexpr gsl::static_bounds<FirstRange, RestRanges ...>::static_bounds(std::initializer_list<long int>)’:
./GSL/include/gsl/multi_span:605:65: error: useless cast to type ‘const ptrdiff_t*’ {aka ‘const long int*’} [-Werror=useless-cast]
: m_ranges(static_cast<const std::ptrdiff_t*>(il.begin()))
^
./GSL/include/gsl/multi_span: In function ‘constexpr gsl::multi_span<U, narrow_cast<long int>(((typename gsl::multi_span<std::byte, Dimensions ...>::bounds_type::static_size != gsl::dynamic_range) ? (static_cast<long unsigned int>(typename gsl::multi_span<std::byte, Dimensions ...>::bounds_type::static_size) / sizeof (U)) : …
```

Fix GCC8 warnings 'useless cast to type'.

---

.travis.yml

Per discussion in #695, added gcc 7 to clang5 and clang 6 configurations.

Added c++17 test configurations for clang5.0 and clang6.0

---

include/gsl/gsl_assert
include/gsl/gsl_util

For this short code snippet
```
#include <gsl/gsl_util>
#include <vector>
void pr642()
{
short buf[3];
std::vector<short> vec(3);
gsl::at(buf, 2) = gsl::narrow<short>(42);
gsl::at(vec, 2) = gsl::narrow<short>(42);
}
```
VS 15.6.2 code analysis generates annoying warnings.
> ...\gsl\include\gsl\gsl_util(93) : warning C26472 : Don't use a static_cast for arithmetic conversions. Use brace initialization, gsl::narrow_cast or gsl::narow (type.1).
> ...\gsl\include\gsl\gsl_util(127) : warning C26472 : Don't use a static_cast for arithmetic conversions. Use brace initialization, gsl::narrow_cast or gsl::narow (type.1).
> ...\gsl\include\gsl\gsl_util(127) : warning C26482 : Only index into arrays using constant expressions(bounds.2).
> ...\gsl\include\gsl\gsl_util(127) : warning C26446 : Prefer …

Suppress warnings on VS

---

include/gsl/gsl_byte

Fix for #713:
GCC > 7.3 defines __cpp_lib_byte >= 201603 when std::byte is available.
On libc++ std::byte is available since version 5.0. This can be checked
with _LIBCPP_VERSION >= 5000.

Explicitly check for availability of std::byte (fixes #713)

---

include/gsl/span
tests/span_tests.cpp

- Fixes runtime issues when constructing from an empty std::array (Issue #685)

Span can be constructed from empty std::array safely

---

CMakeLists.txt

This fixes the issue raised in PR #465. While the proposed solution in #465 depended on compiler-specific macros, this patch uses a build-system feature and therefore does not depend on compiler-specific behaviour.
Additionally, it treats the headers only as system headers for non-standalone builds, so that GSL-developers are still able to see and fix legitimate warnings.

Suppress Warnings in GSL Headers

---

CMakeLists.txt

Fixes #758 by using the correct comparison operator for a version
See documentation at https://cmake.org/cmake/help/latest/command/if.html
Thanks to this change, gsl natvis is properly included in a visual studio solution

Fixes CMAKE_VERSION check

---

include/gsl/span

Added support for `constexpr` range checking to allow for `constexpr span::operator[]` to work in a constant expression.

Make CheckRange constexpr

---

include/gsl/multi_span

Is there a reason `TypeListIndexer` cannot be made constexpr?
```
// requires constexpr createTypeListIndexer
static_assert(static_bounds<3,2>{}.extent<0>() == 3,"");
static_assert(static_bounds<3,2>{}.extent<1>() == 2,"");
static_assert(static_bounds<3,2>{}.extent(0) == 3,"");
static_assert(static_bounds<3,2>{}.extent(1) == 2,"");
```

make TypeListIndexer constexpr

---

include/gsl/gsl_byte

The check for std::byte existance fails on gcc 8.2. According to https://en.cppreference.com/w/cpp/utility/feature_test it is necessary to `#include <cstddef>` before checking `__cpp_lib_byte`.

Fixed check if std::byte is available

---

include/gsl/string_span

This PR fixes issue #798  by  dropping inclusion of `gsl/pointers` in `string_span`.

Fixes #798 : Dropping inclusion of `gsl/pointers` in `string_span`

---

tests/multi_span_tests.cpp
tests/notnull_tests.cpp

I looked through all tests with `valgrind --leak-check=full --leak-kinds=all` and found some memory errors. So this PR is just minor fixes of ones.
--------
Fixes #737. Actually this issue gave me an idea to run valgrind on all files. So thanks to @stayprivates. It's been over a year since this issue is on hold, so i don't know why he/she doesn't PR the solution already.

Fixed memory leaks and out of bound access

---

CONTRIBUTING.md
ThirdPartyNotices.txt

The library is the Guidelines Support Library, not the Guideline Support Library.

Fixing typo "Guideline" as "Guidelines"

---

include/gsl/pointers
tests/no_exception_ensure_tests.cpp
tests/no_exception_throw_tests.cpp

This fixes a couple warnings created during the LLVM build about lack of deduction guides for not_null and strict_not_null. 
LLVM builds are failing recently with this warning:
..\include\gsl/pointers(69,7): note: add a deduction guide to suppress this warning
class not_null
^
..\tests\notnull_tests.cpp(429,22): error: 'not_null' may not intend to support class template argument deduction [-Werror,-Wctad-maybe-unsupported]
Also:
I found while building with Clang on Windows that _MSC_VER is being defined by Clang, which causes compiler errors due to not being able to find gsl::details::get_terminate_handler. I aligned the preprocessor check to match the one defining get_terminate_handler.

fix ctad warning in llvm

---

include/gsl/span
tests/span_tests.cpp

This issue implements the free-standing iterator and size function discussed in https://github.com/microsoft/GSL/issues/810.
Closes https://github.com/microsoft/GSL/issues/810

Implement free-standing (c|r|cr)(begin|end) and ssize functions

---

include/gsl/span

Now that calls to Expects will result in termination, they are able to be marked as noexcept.

Update noexcept in span and span_iterator 

---

include/gsl/span
tests/span_tests.cpp

Re: #828. 
This pr deprecates functions from gsl::span that do not exist in std::span. 
- span::at
- span::operator()
The goal is to reduce friction between usage of std::span and gsl::span. 
These can be removed later.

Deprecate span::at & span::operator(). See #828.

---

include/gsl/span
tests/span_tests.cpp

Re: #828.
This pr adds functions to gsl::span that are missing from the functions defined in std::span.
- span::front
- span::back
The goal is to reduce friction between usage of std::span and gsl::span.

Add span::front and span::back. See #828.

---

tests/CMakeLists.txt

Somewhere along the line exceptions where enabled for the test that should be executed without exceptions.
This restores the original configuration.

Restore disabling of exceptions for MSVC in "no exception tests"

---

tests/CMakeLists.txt
tests/algorithm_tests.cpp
tests/assertion_tests.cpp
tests/at_tests.cpp
tests/bounds_tests.cpp
tests/byte_tests.cpp
tests/multi_span_tests.cpp
tests/notnull_tests.cpp
tests/owner_tests.cpp
tests/span_tests.cpp
tests/strict_notnull_tests.cpp
tests/strided_span_tests.cpp
tests/string_span_tests.cpp
tests/utils_tests.cpp

Only for the test suite. Remove the `#pragma`'s used to suppress compiler warnings.
This brings all the compile flags together in the `tests/CMakeLists.txt`.
In addition compiler/os/version selection is made a bit more specific and unnecessary suppression flags are removed.
A disadvantage is the lack for a clean way in CMake to set flags for specific files.
Thus, some flags are disabled with a wider scope then before.

Compiler warning suppression for tests to CMake

---

include/gsl/pointers
tests/notnull_tests.cpp
tests/strict_notnull_tests.cpp

Moving not_null will replace whatever pointer is stored within with null, which goes against the purpose of not_null.
This change removes the move constructor for not_null.

remove move constructor for not_null.

---

README.md

The package indicated in README.md corresponded to the GNU Scientific Library https://www.gnu.org/software/gsl/

Fix incorrect package name for vcpkg

---

.travis.yml
CMakeLists.txt
README.md
tests/CMakeLists.txt
tests/multi_span_tests.cpp

- Extend CI reach
-  GCC 8 and GCC 9
- LLVM/Clang 8, 9 and 10
- AppleClang / Xcode 9.4, 10.1 and 11.3 (different compilers)
Generate with `-Wdev -Werror=dev --warn-uninitialized`
-  ~~Libc++ with Clang?~~ (already covered by AppleClang)
- Improve Job performance
Get Clang form the Ubuntu packages where available.
- Other
The latest compilers have the best error messages. There is no benefit in running all legacy compilers before the error is fixed.
Same for ending the CI run after a CMake error is found.
GoogleTest uses feature detection for C++11, AppleClang features information is added in [CMake 3.2](https://cmake.org/cmake/help/latest/release/3.2.html#other).

Improve CI with TravisCI

---

tests/multi_span_tests.cpp

Modification of commit 5e21831494ea1a140bee47d0a95fc7b0af6c0c3c.
The new release of GCC 8.4 shows the same issue as 8.3, therefor this PR disables the test triggering the warning for the full GCC 8 branch.
[TravicCI build 1313](https://travis-ci.org/github/microsoft/GSL/builds/672782652)

Suppress GCC 8 "-Warray-bounds" warning

---

include/gsl/multi_span

MSVC compiler warning C4668:
` '__clang__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'`
[TravisCI build 1312](https://travis-ci.org/github/microsoft/GSL/builds/672776982)
p.s. The check for `__clang__` is since LLVM/clang v10 no longer optional, the new flag `-fgnuc-version=0`  makes `__GNUC__` undefined. [[source]](https://releases.llvm.org/10.0.0/tools/clang/docs/ReleaseNotes.html#new-compiler-flags)

Solve MSVC warning C4668: __GNUC__ & __clang__ not defined

---

include/gsl/gsl_byte

cstddef was being included to detect whether GSL_USE_STD_BYTE should be
set to 0 or 1. But if the user provided GSL_USE_STD_BYTE no detection is
required and the header was never included.

Add missing #include if built with GSL_USE_STD_BYTE=1

---

include/gsl/span
include/gsl/span_ext
include/gsl/string_span
tests/span_compatibility_tests.cpp
tests/span_ext_tests.cpp
tests/span_tests.cpp

[LWG3320](https://cplusplus.github.io/LWG/issue3320 ) removes const_iterator and const_reverse_iterator from span. 
This change removes all references to the removed elements.

implement LWG3320

---

CMakeLists.txt

This PR fixes installation on GNU/Linux distributions (and all other Unixes like BSD).
Cmake will find installed configs from `$libdir/cmake` or `$datadir/cmake` directories.

Fixed installation on GNU/Linux distributions

---

include/gsl/span

- suppress " warning C26481: Don't use pointer arithmetic. Use span instead (bounds.1)."
- Please note that the suppression in `end()` does not work with MSVC 16.5.4.

suppress code analysis warning

---

.github/workflows/main.yml
CMakeLists.txt
README.md

GSL and its tests have been verified to build, run, and pass on iOS and Android, see https://github.com/dipidoo/GSL/runs/644183162. However, this requires forcing GTEST_HAS_DEATH_TEST definition on the test. No modifications were necessary within GSL.
googletest does not support EXPECT_DEATH in iOS platform, see how it tests for !GTEST_OS_IOS: https://github.com/google/googletest/blob/0eea2e9fc63461761dea5f2f517bd6af2ca024fa/googletest/include/gtest/internal/gtest-port.h#L592
By forcing GTEST_HAS_DEATH_TEST definition, I found that the test runs normally and successfully. I am unsure what the reasoning behind googletest's Death Test suppression for iOS platform is, but seeing that this is impacts test code only I feel that this definition is within reason. I have reported this issue as …

reflects verification of iOS and Android support

---

GSL.natvis
include/gsl/span

VS 2019 doesn't seem to match -1 for size_t template parameter, as a result dynamic span/basic_string_span/basic_zstring_span show extent as `extent = 4294967295` (for 32-bit builds). This change updates details::extent_type to have static constexpr size_ parameter for non-dynamic span/basic_string_span/basic_zstring_span and simplifies/removes dynamic versions from GSL.natvis
fixes #856

Fix debugger visualizer for Ext=gsl::dynamic_extent

---

.travis.yml
README.md
appveyor.yml
include/gsl/gsl_util
include/gsl/span
include/gsl/string_span
tests/utils_tests.cpp

We have always unofficially said that we support the current and previous version of each compiler. This change will make that officially stated in the readme, updates the CI/CD, and removes some work arounds for various compiler versions N-2 and beyond.  
Changes: 
- remove VS2015 from appveyor matrix and all associated work arounds from the code ie `_MSC_VER < 1910`
- change travis and appveyor to reflect the N and N-1 compiler version support
- update readme
- indicate that Android and iOS support are secondary and failure of that flow will not prevent the acceptance of the code in PR.

compiler support revision

---

include/gsl/span
tests/span_tests.cpp

I noticed while experimenting with std::span that some of the functionality wasn't 1:1 regarding CTAD.
The deduction of container types was missing. The following std::span example compiles without any problems, while the the gsl equivalent does not.
Ex: Current behavior
```c++ 
std::vector v{1,2,3,4}; 
std::span sp{v}; // no problem, compiles
```
```c++ 
std::vector v{1,2,3,4}; 
gsl::span sp{v}; // fails to compile. gsl::span<int>, however does compile
```
By examining the container's value_type in the deduction guide, we're able to deduce the internal type and construct the span. This more closely aligns gsl::span's behavior to std::span.

Adding missing span deduction guides

---

include/gsl/multi_span
include/gsl/pointers

remove msvc < 1910 checks as those versions are no longer supported.
These are the last of the pragma push_macro / pop_macro combos and will close #18

Remove msvc < 1910 checks.

---

include/gsl/gsl_util

Simplify & move `is_same_signedness` into the function.
Remove uneeded `detail` namespace.
Merge 2 `if`'s with a `||`.

Refactor `narrow`.

---

include/gsl/gsl_assert
include/gsl/gsl_byte

Intel C++ Compiler defines the `_MSC_VER` macro, but it doesn't support `[[gsl::*]]` attributes.
This fix makes `GSL_SUPPRESS` expand to nothing on Intel Compiler, solving the following warnings:
```
gsl/span(301): error #3924: attribute namespace "gsl" is unrecognized
GSL_SUPPRESS(bounds.1) // NO-FORMAT: attribute
^
```
This closes #903.

Fix  GSL_SUPPRESS definition on Intel C++ Compiler

---

include/gsl/string_span

Fixes for a few issues recognized while answering https://stackoverflow.com/questions/56874532/using-gslzstring-view-with-c-apis.
- `s[s.size() - 1]` is wrong for empty `s`, so `Expects(s.size() > 0)`
- no hard coded `'\0'`but `value_type{}`
- hard code `empty()` to return `false`
- simplify `as_string_span`: can never be `empty`
- clarify comment on `ensure_z`

zstring_span: fix for Expects, simplify functions

---

tests/CMakeLists.txt

I discovered that pkg-config module gtest_main may be used in environments without Internet access instead downloading and building Google Test framework by GSL tests. For example, the [libgtest-dev][1] package contains the needed gtest_main.pc file.
[1]: https://packages.debian.org/sid/amd64/libgtest-dev/filelist

Search for GoogleTest via pkg-config first

---

include/gsl/pointers

it should be comparable to nullptr, it does not have to be assignable
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#gslview-views says
> not_null<T> // T is usually a pointer type (e.g., not_null<int*> and not_null<owner<Foo*>>) that may not be nullptr. T can be any type for which ==nullptr is meaningful

fix requirement on not_null template

---

include/gsl/gsl_util

Adding `[[nodiscard]]` to `gsl::finally`. 
This version uses a macro approach with the __has_cpp_attribute feature test.

Finally [[nodiscard]] - Version 2

---

include/gsl/gsl_util
tests/utils_tests.cpp

Hi,
I believe that the function finally should be modified because the deduced type is an lvalue reference when we pass it an lvalue. Then the member f_ would be a reference and this would be dangerous if we move a final action out of the created scope.
I propose a fix. What do you think ?

Fix finally when passing a non const lvalue invokable thing

---

include/gsl/gsl_narrow

fixes #927 by adding an implementation for `narrowing_error::what()` which provides the string "narrowing_error"

add what to narrowing_error

---

README.md
include/gsl/string_span

isocpp/cppcoreguidelines#1680 removed string_span from the C++ Core Guidelines. 
This change deprecates `basic_string_span`, `basic_zstring_span`, and all of their derived types.
Edit: as with multi_span and strided_span, string_span will remain deprecated in the GSL for a year before it is removed.

Deprecate string_span

---

include/gsl/span

The original code triggers
> warning C26472: Don't use a static_cast for arithmetic conversions. Use brace initialization, gsl::narrow_cast or gsl::narrow (type.1).
The change eliminates the warning.

eliminate warning, use narrow_cast instead of static_cast

---

include/gsl/pointers

Some embedded/low-profile STL implementations may not provide iostreams (e.g., EASTL). Allow to use <pointer> without iostreams if desired.
Closes #933.

Allow usage on platforms not providing iostreams

---

include/gsl/gsl

narrow() is now in gsl_narrow rather than gsl_util. Include gsl_narrow when exceptions are enabled. Ensures that #include <gsl/gsl> includes entire library as advertised in the documentation.

Include gsl_narrow from gsl and fix comment.

---

include/gsl/span

Suppress "warning C26481: Don't use pointer arithmetic. Use span instead (bounds.1)."

suppress bounds.1

---

CMakeLists.txt
cmake/guidelineSupportLibrary.cmake

If the use has provided the variable CMAKE_CXX_STANDARD use that instead of providing a default cache variable.

Use CMAKE_CXX_STANDARD when available

---

README.md

Using Azure Pipelines badge instead of the Travis-ci and Appveyor badges.

Change build status badges

---

CMakeLists.txt
cmake/guidelineSupportLibrary.cmake
tests/CMakeLists.txt

Abstract adding natvis file.
Move call to find_package(Git) as well as making it required/quiet.
This PR address the issues I was trying to address:
https://github.com/microsoft/GSL/issues/960

Minor cmake changes

---

CMakeLists.txt
cmake/guidelineSupportLibrary.cmake
tests/CMakeLists.txt

Revert "[cmake] Adding options for INSTALL and TEST"

---

CMakeLists.txt
cmake/guidelineSupportLibrary.cmake
tests/CMakeLists.txt

Reintroducing the changes from #964 by @hdf89shfdfs that were reverted in #966. @pr0g found that the change unintentionally removed a line from the Microsoft.GSLConfig.cmake file, which broke `FindPackage`.
I was able to restore the missing line in the config file by moving `include(GNUInstallDirs)` back to the main CMakeLists.txt file.

Reintroduce CMake changes that were reverted in #966

---

CMakeLists.txt
cmake/guidelineSupportLibrary.cmake
include/CMakeLists.txt

It's much nicer and less error prone to just use add_subdirectory to establish the include directory.
Hide the GNUInstallDirs module by placing it in the helper module. The intent being that the main CMakeLists.txt should have a little code as possible. So that readers can quickly understand the project.
Use include_guard() when available in cmake 3.10+

Minor cmake nitpicks

---

tests/CMakeLists.txt

* Do not require Git for build tests
Cloning via Git is not the only path to obtain Google Test framework. In Linux, using a system package manager is the preferred way, and gtest can be installed through APK, APT, DNF, pacman, or many other.
See also: https://github.com/microsoft/GSL/pull/961#discussion_r548959056
* Support standalone tests
The patch makes possible to run auto-tests against globally installed GSL, ignoring local headers. To do this, run CMake in the tests/ folder.
cmake -B build -S tests -DGSL_CXX_STANDARD=14
This feature should not break existing build recipes.

Improve build script for standalone tests

---

.github/workflows/android.yml
.github/workflows/ios.yml
CMakeLists.txt
cmake/guidelineSupportLibrary.cmake
pipelines/steps.yml

Here is the warning currently being produced:
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.19/Modules/GNUInstallDirs.cmake:223 (message):
Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
target architecture is known.  Please enable at least one language before
including GNUInstallDirs.
Call Stack (most recent call first):
cmake/guidelineSupportLibrary.cmake:20 (include)
CMakeLists.txt:4 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
I noted how I fixed the error. This is caused by GNUInstallDirs automatically executing code just by including it.
I also added -Werror=dev to the CI to ensure this never happens again.

Fixing cmake developer warning

---

include/gsl/pointers

Trying `gsl::not_null<char> p2{ 0 };` on VS2019 the current implementation would trigger
>error C2446 : '!=' : no conversion from 'nullptr' to 'int'
>message: A native nullptr can only be converted to bool or , using reinterpret_cast, to an integral type
>message: see reference to class template instantiation 'gsl::not_null<char>' being compiled
>error C2955 : 'std::is_convertible' : use of class template requires template argument list
>message: see declaration of 'std::is_convertible'
>error C2039 : 'value' : is not a member of 'std::is_convertible<_From,_To>'
>error C2065 : 'value' : undeclared identifier
The new implementation gives much shorter and clearer message and does exactly as the `static_assert` intends to do:
> error C2338: T cannot be compared to nullptr.
> message : see …

is_comparable_to_nullptr for better static_assert

---

include/gsl/assert
include/gsl/gsl_algorithm
include/gsl/narrow
include/gsl/pointers
include/gsl/span
include/gsl/span_ext
include/gsl/util
tests/algorithm_tests.cpp
tests/assertion_tests.cpp
tests/at_tests.cpp
tests/byte_tests.cpp
tests/deathTestCommon.h
tests/notnull_tests.cpp
tests/owner_tests.cpp
tests/span_compatibility_tests.cpp
tests/span_ext_tests.cpp
tests/span_tests.cpp
tests/strict_notnull_tests.cpp
tests/string_span_tests.cpp
tests/utils_tests.cpp

Changed the file location of gsl::span specialization for gsl::at from <gsl/span_ext> to <gsl/span>, addressing #983.
Changed first parameter of gsl::span specialization for gsl::at to take the span by reference, addressing #984.

gsl::at behavior change regarding gsl::span

---

include/gsl/narrow
tests/utils_tests.cpp

Resolves #900.
Supersedes #917.
In the original overload, `((t < T{}) != (u < U{}))` is only ever reached when `is_different_signedness` is `true`, which is only ever `true` for arithmetic types because the same applies to `std::is_signed<T>::value` which `is_different_signedness` is initialized from. So we use `std::is_arithmetic<T>::value` to add an overload.

feat: narrow for non totally ordered types

---

include/gsl/util

For instance, clang 10 sets __cplusplus >= 202002L yet does not have span, which causes build errors: 
https://gcc.godbolt.org/z/Yq345zGea

Fix gsl/util for c++20 compilers without <span>

---

tests/CMakeLists.txt.in

Fixes https://github.com/microsoft/GSL/issues/1014. The issue was resolved in https://github.com/google/googletest/pull/3024. Pulling latest googletest.

Fix build failure with gcc 11+

---

README.md
azure-pipelines.yml
include/gsl/util
pipelines/jobs.yml
pipelines/steps.yml
tests/CMakeLists.txt
tests/algorithm_tests.cpp
tests/at_tests.cpp
tests/span_compatibility_tests.cpp
tests/span_ext_tests.cpp
tests/span_tests.cpp
tests/string_span_tests.cpp

The C++2020 features (`std::span` support) were not enabled in the CI. As a result, the code had compilation issues that were never caught. Furthermore, the compiler versions in the README did not match up to the compilers that were actually being tested. For instance, the minimum GCC version advertised is 8, but we are testing 7.5.0 instead. The precise versions we *should* be testing will be re-visited in a later PR. But for now, this PR simply updates the README to be accurate to what is currently being tested.
Compiler | Advertised (before this PR) | Actually Tested
:------- | :-- | :-- 
XCode |11.4 & 10.3 | 12.4 & 11.3 
GCC |9 & 8| 9.3.0 & 7.5.0 
Clang |11 &  10 | 11.0.0 & 9.0.0
Visual Studio with MSVC | VS2017 (15.9) & VS2019 (16.4) | VS2017 (15.9.21) & VS2019 (16.11.2)
Visual …

Fix/implement C++2020 compilation, tests, and CI

---

CMakeLists.txt

Fixed wrong version number in exported CMake configs.
Closes #1026.

Fixed wrong version number in exported CMake configs

---

include/gsl/algorithm
include/gsl/gsl
include/gsl/gsl_algorithm
include/gsl/gsl_assert
include/gsl/gsl_byte
include/gsl/gsl_narrow
include/gsl/gsl_util
include/gsl/narrow
include/gsl/pointers
include/gsl/span
include/gsl/span_ext
include/gsl/string_span
include/gsl/util

[SF.12: Prefer the quoted form of #include for files relative to the including file and the angle bracket form everywhere else](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rs-incform)
Additionally changed #include order in `span` so that all `span_ext` is in the GSL include block and not in the STL include block.
Fixes issues #1025.

quoted form of #include when GSL includes GSL files

---

include/gsl/narrow
tests/CMakeLists.txt
tests/utils_tests.cpp

`-Wfloat-equal` is concerned with the floating-point comparison in `gsl::narrow`. However, the use of this comparison is by design.
Resolves #1038

Suppress -Wfloat-equal warning

---

include/gsl/narrow

This file uses std::exception, so it should include the appropriate header.
Normally it gets the STL's "exception" header included via the gsl/assert file, but this is skipped with _HAS_EXCEPTIONS=0. I understand _HAS_EXCEPTIONS is undocumented and unsupported, but regardless, the appropriate header should be included here.
Alternatively, gsl/narrow should be modified to support _HAS_EXCEPTIONS=0, like gsl/assert was. But I'm not proposing that change. "exception" does define std::exception even with _HAS_EXCEPTIONS=0.

gsl/narrow should include <exception>

---

include/gsl/narrow

As per the CoreGuidelines, gsl::narrow is defined in terms of static_cast.
Suppress es.46, which suggests converting the static_cast into gsl::narrow.
This resolves #1036

Suppress es.46 warning in implementation of gsl::narrow

---

include/gsl/span_ext
include/gsl/util

MSVC warning C5260 says namespace-scope `constexpr` variables should be marked `inline` or `static` for C++20 header units. 
("warning C5260: the constant variable 'X' has internal linkage in an included header file context, but external linkage in imported header unit context; consider declaring it 'inline' as well if it will be shared across translation units, or 'static' to express intent to use it local to this translation unit").

Resolve MSVC warning C5260

---

.github/workflows/android.yml

This PR future-proofs the fix made in https://github.com/microsoft/GSL/pull/1053, which is now outdated due to further updates to the NDK version in the Azure VMs used as part of the CI.

Fix NDK version in Android CI

---

include/gsl/util
tests/utils_tests.cpp

`finally` needs to use `decay_t` instead of `remove_cvref_t` so it can properly accept non-object function arguments by decaying to function pointer type. Adds test coverage for this use case which was previously missing.

Properly handle finally(actual_function)

---

include/gsl/pointers
tests/notnull_tests.cpp

Issue https://github.com/microsoft/GSL/issues/550 highlighted overhead in `not_null::get` for larger types such as `shared_ptr`. Every call to `get` would return a copy of the contained value. 
This PR implements Herb's suggestion for changing the return type of `not_null::get`. The `not_null`'s value will now only be copied if it is "trivially copyable"; otherwise, it will be returned by const reference. 
Note: this change also forces the returned copy to be `const`.

Prevent inefficient copying when using not_null::get

---

CMakeLists.txt
README.md
cmake/gsl_functions.cmake
cmake/gsl_install.cmake
include/CMakeLists.txt

- Move all install logic inside gsl_install.cmake
- This makes reading the logic easier, and avoids the enable language issue with `GNUInstallDirs` by having it included after the project call
- Have all functions inside gsl_functions.cmake
- Use CMake idiom PROJECT_IS_TOP_LEVEL
- Update README.md

CMake cleanup

---

CMakeLists.txt
README.md
cmake/gsl_functions.cmake
tests/CMakeLists.txt

This avoids propogating -std=c++14 as a compile option
Currently if you use less than CMake 3.8 and you install the project
`-std=c++14` gets added to the INTERFACE_COMPILE_OPTIONS. This forces
users to use C++ 14 or remove the property from the imported target.
The solution is to raise the minimum and use `cxx_std_14`

Raise CMake min to 3.8

---

include/gsl/pointers
include/gsl/string_span

I ran GSL through clang-tidy with the performance-* checks
https://releases.llvm.org/15.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance/noexcept-move-constructor.html

clang-tidy: performance-noexcept-move-constructor

---

include/gsl/assert
include/gsl/byte

This change is very similar to #906. It seems that nvcc compiler, though is it based on msvc, does not support this namespace. 
Sample build:
https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=802911&view=logs&j=6df8fe70-7b8f-505a-8ef0-8bf93da2bac7&t=38e4b5a4-9041-5949-6670-6ace666c420b&l=4492
Error message:
D:\a\_work\1\b\RelWithDebInfo\_deps\gsl-src\include\gsl\util(101,0): Error #2803-D: attribute namespace "gsl" is unrecognized
It happens only when compiling *.cu files.
The command that generated the above warning:
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe" -gencode=arch=compute\_75,code=\"compute\_75,compute\_75\" -gencode=arch=compute\_75,code=\"sm\_75,compute\_75\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual …

Fix GSL_SUPPRESS definition when nvcc is in-use

---

tests/CMakeLists.txt

The Clang compiler for MSVC in Visual Studio 2022 17.4.33122.133 used by the test runner has a bug which raises -Wdeprecated "out-of-line definition of constexpr static data member is redundant in C++17 and is deprecated" in gsl/span, when compiling with C++14. Temporarily suppress this warning for MSVC Clang with C++14.

Suppress false postive warning

---

include/gsl/pointers

[Guidelines issue 2006](https://github.com/isocpp/CppCoreGuidelines/issues/2006) removes the null check inside `not_null::get`, since the contained pointer is already guaranteed to be not-null upon construction. 
Resolves #1051

Remove null-check Expects assertion inside not_null::get

---

include/gsl/narrow

NaN != Nan, so the comparisons used in `gsl::narrow` will always throw when attempting to cast a NaN value. This may be surprising, so document it.
Resolves https://github.com/microsoft/GSL/issues/1069

Document potentially confusing behavior in gsl::narrow

---

GSL.natvis
tests/assertion_tests.cpp

- `fail_fast`,`basic_string_span` and `basic_zstring_span` are not declared in the headers any more.
- Name the exporting header file for all types in `GSL.natvis`.

cleanup natvis

---

.gitattributes

Add a `linguist-language` Git attribute that matches the files at `include/gsl` and sets their language to C++. Without this override, these files are not detected as C++ code by [GitHub's Linguist](https://github.com/github/linguist) (likely due to lacking any file extensions).
This will cause GitHub.com to count these files correctly as C++ code and do syntax highlighting when browsing the repo.
**Linguist breakdown results**
Before:
<details>
```
$ docker run --rm -v $(pwd):$(pwd) -w $(pwd) -t linguist github-linguist --breakdown
91.57%  152148     C++
8.43%   14011      CMake
CMake:
CMakeLists.txt
cmake/gsl_functions.cmake
cmake/gsl_install.cmake
include/CMakeLists.txt
tests/CMakeLists.txt
C++:
tests/algorithm_tests.cpp
tests/assertion_tests.cpp
tests/at_tests.cpp
tests/byte_tests.cpp …
```

Add Linguist language override for include files

---

include/gsl/util
tests/at_tests.cpp
tests/span_ext_tests.cpp

https://github.com/microsoft/GSL/issues/1075
- Add `static_assert` because we only support C style array `at` for up to half of the address space.
- Add `std::` before `size_t`.
- tests:
- Add `#include <exception>`
- Implement `span_tests` `interop_with_gsl_at` like `at_tests` `std_span`

1075 Wrong Expects in gsl::at?

---

include/gsl/util

PR https://github.com/microsoft/GSL/pull/1076 introduced a usage of `numeric_limits::max()` function, which seems to have [issues interacting with some Windows headers](https://github.com/skypjack/entt/wiki/Frequently-Asked-Questions#warning-c4003-the-min-the-max-and-the-macro). This PR implements [a simple fix](https://stackoverflow.com/questions/1394132/macro-and-member-function-conflict), which is to wrap the invocations in parentheses. This offloads the fix from the users of the library.

Fix `max` macro collision

---

tests/notnull_tests.cpp
tests/strict_notnull_tests.cpp

While writing the docs I found a `remove_cv_t` in `make_null`/`make_strict_not_null` which made me wonder if we want to make sure that the code works well with const pointers.

add not_null and strict_not_null tests for const

---

docs/headers.md

The `#i13-do-not-pass-an-array-as-a-single-pointer` anchor seems to be auto generated based on the title of the section. The `#Ri-array` anchor is explicitely written in the source, so this should be a better link.

Better links to CoreGuidelines

---

docs/headers.md

`<gsl/span>` is intended to mirror `<span>` in the STL. `<span_ext>` provides convenience features that aren't part of `<span>`.
Address #1095

Update documentation of span_ext

---

README.md

- Capitalize inital letter (make both tables consistent)
- Add links to docs/headers.md
- Latest cmake requirement is 3.14
- Mark text as code

minor docs improvements

---

include/gsl/span

@tiagomacarios encountered the following error:
```
C:\Temp>type meow.cpp
```
```cpp
#include <algorithm>
#include <gsl/span>
#include <iostream>
int main() {
int arr[]{1, 7, 2, 9};
gsl::span sp{arr, std::size(arr)};
std::ranges::sort(sp);
for (const auto& e : sp) {
std::cout << e << ", ";
}
std::cout << "\n";
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /MTd /Od /std:c++latest /I GSL\include meow.cpp && meow
meow.cpp
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.36.32323\include\algorithm(8268): error C2678: binary '-': no operator found which takes a left-hand operand of type '_Sent' (or there is no acceptable conversion)
with
[
_Sent=gsl::details::span_iterator<int>
]
```
<details>
<summary>Click to expand error context (which explains the proximate error, but in a …

Fix `span_iterator` unwrapping for MSVC

---

include/gsl/span

Suppress "warning C26481: Don't use pointer arithmetic. Use span instead (bounds.1)." in the code that impements `span`.

Suppress warning C26481

---

include/gsl/span
tests/span_tests.cpp

`size_bytes()` returns the span's size in bytes. 
Assuming the span was constructed with an accurate size parameter, the check `size() < dynamic_extent / sizeof(element_type)` isn't required, since `size_t(-1)` (which is `dynamic_extent`) represents the size of the address space, so the number of bytes will never exceed it and in practice won't even come close.
Otherwise, it is not actually feasible to detect cases when the size parameter does not correspond to the dimensions of the underlying data pointer. In these cases, the relationship `size() < dynamic_extent / sizeof(element_type)` is simply one of many ways in which the `size()` could be incorrect, and serves no necessary purpose.
Resolves #1012

Remove unnecessary check from size_bytes()

---

include/gsl/pointers

Using `<`,`<=`,`>`,`>=` to compare unrelated pointers gives an unspecified result according to standard.
This PR replaces the usage of these operators in `gsl::not_null` with the STL counterparts, which would leverage any implementation-defined strict total ordering for pointers.
Resolves #880

Use the implementation-defined strict total order for pointer comparisons with `not_null`

---

include/gsl/pointers

Disable `std::hash<gsl::not_null<T>>` if `std::hash<T>` is not enabled.
Resolves #914

Only enable std::hash<gsl::not_null<T>> if std::hash<T> is enabled.

---

include/gsl/span_ext

These overloads don't seem to be in a usable state, and their original purpose is no longer clear. Prepare to remove them via deprecation.
Resolves #1092

Deprecate the smartpointer make_span overloads

---

include/gsl/gsl_algorithm
include/gsl/gsl_assert
include/gsl/gsl_byte
include/gsl/gsl_narrow
include/gsl/gsl_util

Headers that were previously prefixed with `gsl_` were renamed to drop the `gsl_` prefix in https://github.com/microsoft/GSL/pull/946, and the original version deprecated.
The deprecation happened a long time ago, so it is now time to remove these headers entirely.

Remove deprecated headers

---

include/gsl/pointers

Without this change a `gsl::not_null<class_type>` triggers these `noexcept` warnings:
```
.../gsl/include/gsl/pointers:162:50: warning: noexcept-expression evaluates to ‘false’ because of a call to ‘constexpr gsl::details::value_or_reference_return_t<T> gsl::not_null<T>::get() const [with T = class_type*; gsl::details::value_or_reference_return_t<T> = class_type* const]’ [-Wnoexcept]
162 |                 const not_null<U>& rhs) noexcept(noexcept(lhs.get() == rhs.get()))
|                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../gsl/include/gsl/pointers:119:55: note: but ‘constexpr gsl::details::value_or_reference_return_t<T> gsl::not_null<T>::get() const [with T = class_type*; gsl::details::value_or_reference_return_t<T> = class_type* const]’ does not throw; …
```

remove gcc noexcept warning

---

include/gsl/pointers

The header file uses `std::declval`, so it needs to `#include <utility>`.

add missing include

---

include/gsl/pointers

Before my PR #1122 `gsl/pointers` was gcc 8.4 compatible. Now it is not. This commit makes it compatible with gcc 8.4 again.

get back gcc 8.4 compatibility

---

include/gsl/assert

This macro is a relic of the old implementation of GSL's <assert> header. It is unused and can be removed.

Remove unused macro GSL_STRINGIFY

---

README.md
docs/headers.md

- Add anchor for `finally` in `headers.md` so that the link in `README.md` can work
- In `README.md` add code formatting for the character types of the `zstring` and `string_span` types
- In `README.md` change code formatting to links for GSL types
- Vertical alignment

fix and optimize documentation

---

include/gsl/span
tests/CMakeLists.txt

Two warnings were being emitted in the MSVC+LLVM tests. 
The warning `-Wunsafe-buffer-usage` is initially introduced in some capacity here https://reviews.llvm.org/D137346 pointing to documentation at https://discourse.llvm.org/t/rfc-c-buffer-hardening/65734. The warning is a stylistic checker whose goal is to "emit a warning every time an unsafe operation is performed on a raw pointer". This type of programming model is not useful for library implementations of types such as `span`, where direct manipulation of raw pointers is inevitable, so disable the warning altogether.
There is also a false-positive warning https://github.com/llvm/llvm-project/issues/65689 that I've disabled inline.

Suppress some noisy / buggy warnings

---

include/gsl/assert
include/gsl/byte
tests/byte_tests.cpp

Update Clang GSL_SUPPRESS to stringize parameter instead of using fixed string literal.

---

include/gsl/pointers
tests/notnull_tests.cpp

This enables possible optimisations for trivial types. This also avoids a bug in std::variant::emplace from GNU's libstdc++.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106547
Closes: #1134

Mark not_null constructors as noexcept when underlying type can be moved with no exception

---

.github/workflows/android.yml
.github/workflows/cmake_find_package.yml
.github/workflows/ios.yml

This fixes annotations on task runs like the following:
The following actions uses node12 which is deprecated and will be forced
to run on node16: actions/checkout@v2. For more info:
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

ci: Update to `actions/checkout@v4`.

---

include/gsl/span
include/gsl/util
tests/CMakeLists.txt
tests/span_tests.cpp

Fix initialization in test

---

include/gsl/byte

Long-awaited followup to #822 which addressed #821.
[GSL 4.0.0](https://github.com/microsoft/GSL/releases/tag/v4.0.0), released 2 years ago, dropped support for VS 2017. Only VS 2019 and VS 2022 are supported. Therefore, GSL can now always use the Standard feature-test macro `__cpp_lib_byte` to sense whether MSVC's STL provides `std::byte`. It should no longer inspect the non-Standard macro `_HAS_STD_BYTE` (which is our "control macro").

Inspect only `__cpp_lib_byte`, drop `_HAS_STD_BYTE`

---

.github/workflows/android.yml
tests/CMakeLists.txt

Job has been failing for months and is preventing other PRs from getting
merged. This PR fixes the pipeline - it changed the following:
- runs on macos-latest-large (which is a non-arm image)
- starts the emulator under java8 (see
https://learn.microsoft.com/en-us/java/openjdk/transition-from-java-8-to-java-11)
- runs emulator with -no-audio
The above were requirements to get the pipeline running. Other changes
include the following:
- The job will auto-cancel when a newer commit is pushed to the
PR.
- The 'Wait for emulator ready' step now has a 2 minute timeout. This
is necessary because we get no indication on whether or not the
command that started the emulator suceeded. I believe there is room
for improvement here, but it is outside the scope of the PR.

[ci]: fix android job

---

include/gsl/span
include/gsl/util

Closes issue #1148 by fixing problems introduced in PR #1140.

Fix gcc build problem

---

README.md

Adds a comment and link to the bottom of the `README.md` for details on a different GSL at Microsoft.

Add a MS GSL disambiguation note

---

include/gsl/span

Issue: #1165
Before this PR, the range-for loop was ~3300x slower. After this PR, it is ~1.005x slower
The clang optimizer is very good at optimizing `current != end`, so we changed to this idiom. This moves the Expects assertion into the constructor instead of on the hot-path which is called whenever either operator++ or operator* is called.
Note: The codegen for the assertion is still a missed optimization, but less worrisome as it only happens once per iterator.

improve performance of span_iterator w/ clang

---

.github/workflows/android.yml
.github/workflows/compilers.yml
tests/CMakeLists.txt
tests/CMakeLists.txt.in

CI checks are failing because the cmake version requires cmake minimum requires >= 3.10. This PR addresses that issue.
Looks like https://github.com/actions/runner-images/issues/10703 took away support for xcode 14. That is why the latest action failed. There an active PR adding support for xcode 16 to the macos runner (https://github.com/actions/runner-images/pull/10967). This commit will fail until that has been merged, but it is probably worth waiting for. Edit: Looks like that PR was closed, so we won't wait.

fix various pipeline failures

---

README.md

* update pipeline badge links
* add link to compilers pipeline
* add badge to vcpkg version

fix stale badge links in README

---

include/gsl/pointers

`std::enable_if_t` must not be used as a default template argument, otherwise the instantiator will be able to override it freely with something that doesn't fail substitution. Instead, `std::enable_if_t` itself must be the type of the template argument.
More information in the examples here: https://en.cppreference.com/w/cpp/types/enable_if

Fix SFINAE on `gsl::owner`.

---

include/gsl/pointers

fixes: https://github.com/microsoft/GSL/issues/1162
gcc has a bug that generates a call to the copy constructor when list initializing a const reference. This PR offers a workaround which is to direct initialize the value.
see: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117900

fix: direct-init const ref instead of list-init

---

docs/headers.md
include/gsl/pointers
include/gsl/util
tests/CMakeLists.txt
tests/pointers_tests.cpp

fixes: https://github.com/microsoft/GSL/issues/1129
* create gsl::swap<T>(T&, T&) which wraps std::swap
* specialize gsl::swap<T>(gsl::not_null<T>&, gsl::not_null<T>&)
* add tests

introduce gsl::swap for swapping gsl::not_null

---

tests/byte_tests.cpp

When setting `GSL_USE_STD_BYTE` to zero, then the unit test does not compile because `byte` is ambiguous (could be `std::byte` or `gsl::byte`). So `gsl::` prefix is needed for `byte`.
It looks like the unit tests never ran on a platform where `gsl::byte` is not based on `std::byte`.
It does not make much sense to test `std::byte` for compliance, so make the unit tests based on the GSL implementation of `gsl::byte` (`#define GSL_USE_STD_BYTE 0`).

Force unit tests for byte to use GSL implementation

---

docs/headers.md
include/gsl/byte
include/gsl/pointers
tests/byte_tests.cpp
tests/pointers_tests.cpp
tests/span_compatibility_tests.cpp

Replace all occurances of `class = std::enable_if_t<Cond>` and `typename = std::enable_if_t<Cond>` with `std::enable_if_t<Cond, bool> = true`.
This commit is inspired by #1174, which changed one occurance in the owner header. This commit is aimed to fix all remaining occurances.

Better use of std::enable_if

---

include/gsl/pointers
tests/notnull_tests.cpp
tests/pointers_tests.cpp
tests/strict_notnull_tests.cpp

- `strict_not_null<std::unique_ptr<int>>{ std::make_unique<int>()}` failed to compile
- `strict_not_null` ctor needs to move the passed `unique_ptr`, not copy
- Copied `not_null` `TestNotNullConstructors` for `strict_not_null`
- The `noexcept` specifiers on the `strict_not_null` and `not_null` constructors were out of sync.
- Added unit test for `not_null<unique_ptr<T>>` and for `strict_not_null<unique_ptr<T>>`
- Added unit test for `gsl::swap` for two `strict_not_null`
- Added unit test for `gsl::swap` for `not_null` and `strict_not_null`

strict_not_null for unique_ptr

---

.github/workflows/compilers.yml
README.md

Reacting to https://github.com/actions/runner-images/issues/10636
* update clang to 16,17,18
* update gcc to 12,13,14

React to ubuntu-latest changing to 24.04

---

include/gsl/span
tests/algorithm_tests.cpp
tests/byte_tests.cpp
tests/notnull_tests.cpp
tests/owner_tests.cpp
tests/pointers_tests.cpp
tests/span_tests.cpp
tests/strict_notnull_tests.cpp

- Bugfix: templated versions of span::first(), span::last() and span::subspan() now fail to compile if more elements than available are being extracted from a static sized span; previously it compiled and `Expects` failed during runtime
- Remove some of the checks in `#ifdef CONFIRM_COMPILATION_ERRORS` and add compile time checks for these tests.
- Acitvate some commented out checks.
- Activate some deactivated checks depending on the platform
- Make some death checks simpler to only check the function call that is needed to trigger the death.
- clang-format

More checks for non-compilable code, plus fix for span

---

include/gsl/algorithm
include/gsl/gsl
include/gsl/narrow
include/gsl/pointers
include/gsl/span
include/gsl/span_ext
include/gsl/util
include/gsl/zstring

Reverts commit that changes #include "assert" -> #include "gsl/assert". This change is necessary in order to comply with CppCoreGuideline's SF.12. Now we do #include "./assert".
fixes https://github.com/microsoft/GSL/issues/1188

use relative path in # include

---

README.md
include/gsl/byte
include/gsl/pointers
include/gsl/span
include/gsl/span_ext
include/gsl/util

1) Mark the following GSL features as deprecated:
- gsl::unique_ptr (always)
- gsl::shared_ptr (always)
- gsl::byte (since c++17)
- gsl::joining_thread (never implemented)
2) Refactor existing deprecations to use the new GSL_DEPRECATED(msg) macro.
3) Create a section in the README for deprecated features in the
standard.

deprecate features adopted into C++

---

README.md
docs/headers.md

- reintroduce documentation internal links
- remove `gsl::` prefix in table so it is the same as in the other tables
- fix documentation for span::element_type

documentation

---

include/gsl/byte
include/gsl/span

- A macro with the very generic name `BYTE_TYPE` is likely to collide with existing code, so get rid of the macro.
- The new solution is to provide a non-deprecated `byte` in the namespace `gsl::impl`.
- Users of GSL should use `gsl::byte`, which is still deprecated when mapped to a `std::std::byte`.
- GSL types and functions need to use `gsl::impl::byte` so they do not trigger the deprecation warning.
- The `gsl::impl::byte` return type in an exported function is not nice, it might mislead users to use that type in their own declarations. But the `BYTE_TYPE` solution is not better in this respect.

replace BYTE_TYPE with a solution based on namespaces

---

include/gsl/pointers

Fixes: #1204 
- Allow returning by value for types that are not greater than two pointers in size

Update return by value threshold in gsl::not_null
