tests/CMakeLists.txt

With this function we can avoid duplicated code to add a new test.

Add add_gsl_test() function in tests/CMakeLists.txt

---

.travis.yml
CMakeLists.txt
README.md
tests/CMakeLists.txt

Implements #27
To activate testing:
- before accepting this PR please enable this repo at https://travis-ci.org/
- merging the PR will trigger a travis run

add travis testing (gcc5, clang36)

---

include/array_view.h
include/fail_fast.h
include/gsl.h
include/string_view.h

Fix issue #39: Add header guards

---

include/array_view.h

Corrects previous commit. Never mix football and PRs ;-)

Correct fix for int/size_t mismatch.

---

include/gsl.h
tests/maybenull_tests.cpp
tests/notnull_tests.cpp

Add various copy assignment operators to not_null and maybe_null_*.

---

include/array_view.h
include/fail_fast.h
include/gsl.h
include/string_view.h
tests/CMakeLists.txt
tests/array_view_tests.cpp
tests/assertion_tests.cpp
tests/at_tests.cpp
tests/bounds_tests.cpp
tests/maybenull_tests.cpp
tests/notnull_tests.cpp
tests/owner_tests.cpp
tests/string_view_tests.cpp
tests/utils_tests.cpp

Renamed namespace to 'gsl'. Renamed macro to configure testing.

---

include/array_view.h

Use of algorithms in the STL should be promoted where possible.
Also fixed up some whitespace issues.

We should be using standard algorithms where possible.

---

include/gsl.h

Just added std::hash support: std::hash&lt;gsl::not_null&lt;T&gt;&gt;

std::hash support for gsl::not_null.

---

include/string_span.h
tests/string_span_tests.cpp

This PR should fix the remaining compiler crash reported in #159.

Added workaround for MSVC 2013 compiler bug.

---

include/span.h
tests/CMakeLists.txt
tests/bounds_tests.cpp
tests/notnull_tests.cpp
tests/span_tests.cpp
tests/string_span_tests.cpp

Ensuring we demonstrate what we preach :-)

Turning on max warning levels for compilation.

---

include/span.h
tests/span_tests.cpp

as_span(str) returns cstring_span regardless of constness of str #192

---

include/string_span.h
tests/string_span_tests.cpp

VS2013 compilation break fixes. Made sure that we don't compile the code that is supposed not to compile.

Fixed compilation issues in MSVC 2013

---

include/gsl_util.h
tests/utils_tests.cpp

Fixes https://github.com/Microsoft/GSL/issues/222.

narrow: check for changed sign

---

include/gsl_assert.h

Fix: Issue: #267 gsl::fail_fast only defined for one configuration

---

CMakeLists.txt

Added install command for gsl header files.
I've set the install directory to include/gsl but happy to change it to something else.

Add CMake install target for header files

---

include/multi_span.h
tests/multi_span_tests.cpp
tests/strided_span_tests.cpp

All tests pass with GCC 5.3 on Windows. I have not tested other compilers.
I modified all tests to use the new syntax. I have not added any new tests to ensure that the old style still compiles but I did check that it does.

Implemented https://github.com/Microsoft/GSL/issues/260

---

gsl/string_span
tests/string_span_tests.cpp

See #247 
Tested on 2015 RC3 and gcc version 6.2.0 20160830.

Add to_basic_string

---

.travis.yml

* Build on OSX with Xcode 8
* Build on Linux with Clang 3.6/7/8 and libc++
* Build on Linux with GCC 5/6

[Travis] enlarge the support matrix

---

gsl/span

Don't const-qualify span::const_iterator's value_type

---

.travis.yml
appveyor.yml

Travis: use cmake 3.7
Appveyor: Add .appveyor.yml config, test VS2013/VS2015/VS2017 x86/x64 Debug/Release.
I think @neilmacintosh may need to fix his AppVeyor configuration and tell it to simply use appveyor.yml.

CI updates:

---

include/gsl/gsl
tests/notnull_tests.cpp

Fix for issue #491 
Also added relevant test

Adding derference operator to not_null

---

include/gsl/gsl
tests/notnull_tests.cpp
tests/owner_tests.cpp

Also added basic test for a simple case for integer

Restricting usage of owner<T> to pointer types

---

tests/span_tests.cpp

extended test case for span/pointer length contructor

additional span tests (pointer length constructor)

---

include/gsl/gsl
include/gsl/gsl_algorithm
include/gsl/gsl_assert
include/gsl/gsl_util
include/gsl/multi_span
include/gsl/pointers
include/gsl/span
include/gsl/string_span
tests/algorithm_tests.cpp
tests/assertion_tests.cpp
tests/at_tests.cpp
tests/bounds_tests.cpp
tests/byte_tests.cpp
tests/multi_span_tests.cpp
tests/notnull_tests.cpp
tests/owner_tests.cpp
tests/span_tests.cpp
tests/strided_span_tests.cpp
tests/string_span_tests.cpp
tests/utils_tests.cpp

I ran it with the --comment flag to get clangs reasoning for the include.
Should fix #583 and supersedes #584.
@paweldac @LegalizeAdulthood wdyt?

runs iwyu on the code base

---

include/gsl/gsl

Added missing gsl headers(algorithm and byte) to gsl header file.
fixes: https://github.com/Microsoft/GSL/issues/500

added gsl_algorithm and gsl_byte headers to gsl header

---

tests/notnull_tests.cpp

minor extension to `notnull` constructor tests

add throw on nullptr CTOR test

---

include/gsl/gsl_assert

Making terminate handler __cdecl.

make terminate_handler  __cdecl

---

.travis.yml
CMakeLists.txt
appveyor.yml
tests/CMakeLists.txt

Added running latest compilers with -std=c++17 option to CI the test matrix,
Updated cmake configuration to allow passing c++ standard on the command line.

Added testing for c++17 to latest compilers with test with

---

tests/span_tests.cpp

Test broken size

---

include/gsl/gsl_util
tests/utils_tests.cpp

I hope Visual Studio 2015 works.

Make narrow constexpr

---

include/gsl/string_span

add value_type size_type for string_span

---

appveyor.yml

Refer to https://github.com/appveyor/ci/issues/2907
VS2019 is enabled per request.

Add Visual Studio 2019 image for tests

---

include/gsl/gsl_util

Fix GNUC typo

---

include/gsl/span

About my Issue - https://github.com/Microsoft/GSL/issues/765

Update usage of difference_type in span

---

include/gsl/gsl_byte

Adding a check to __cpp_lib_byte to gsl_byte, which will resolve issue #821 and by enable microsoft/stl#204 to be addressed.
Is this what you had in mind @stephantlavavej?

gsl_byte to inspect __cpp_lib_byte 

---

tests/algorithm_tests.cpp
tests/assertion_tests.cpp
tests/at_tests.cpp
tests/bounds_tests.cpp
tests/byte_tests.cpp
tests/multi_span_tests.cpp
tests/notnull_tests.cpp
tests/owner_tests.cpp
tests/span_tests.cpp
tests/strict_notnull_tests.cpp
tests/strided_span_tests.cpp
tests/string_span_tests.cpp
tests/utils_tests.cpp

added suppression for missing destructor override

fix appveyor build issues.

---

CMakeLists.txt

Preparing to create official release version 3.1.0 of GSL.

Update project version to GSL 3.1.0 

---

include/gsl/span
include/gsl/string_span

Remove gsl namespace qualification within the gsl namespace
This closes #888.

cleanup gsl namespace qualification for dynamic_extent.

---

README.md

Hello!
I believe it would compose nicely with https://github.com/isocpp/CppCoreGuidelines/pull/1516.
And please help me with `strided_span` cause I have no idea what that beast might be.

Add a table of features

---

include/gsl/pointers

Implemented the changes suggested by @jwakely in https://github.com/microsoft/GSL/pull/842#issuecomment-673419182

not_null improvements

---

include/gsl/string_span

Added constexpr to a few functions in string_span.

constexpr string_span

---

.github/workflows/android.yml
.github/workflows/ios.yml
README.md

split GitHub action into multiple files.

---

CMakeLists.txt

added GSL_ prefix to VS_ADD_NATIVE_VISUALIZERS

---

azure-pipelines.yml
pipelines/jobs.yml
pipelines/steps.yml

Azure pipeline

---

.github/workflows/android.yml
.github/workflows/ios.yml
CONTRIBUTING.md
README.md
azure-pipelines.yml

There were a few files that needed to be updated with the new primary branch name.

Branch rename cleanup

---

README.md
azure-pipelines.yml
pipelines/setup_apple.yml

Bump clang support to 12 and 11, and add support for VS with LLVM

Update compiler support

---

include/gsl/narrow

See https://github.com/microsoft/GSL/issues/786

Document safe usage of undefined behavior in gsl::narrow

---

include/gsl/span

Addresses https://github.com/microsoft/GSL/issues/1013

Remove useless check against `dynamic_extent`

---

README.md
docs/headers.md
include/gsl/assert
include/gsl/pointers

This is a first (partial) shot for issue #1071.

Documentation

---

tests/span_tests.cpp

More combinations with dynamic_extent or fixed extent for higher coverage.

add some span test for constructor from other span

---

CMakeLists.txt
README.md

Fixes: https://github.com/microsoft/GSL/issues/1161
Update version strings in README and CMakeLists.txt.

GSL v4.1.0
